language: r
sudo: required
cran: http://cran.rstudio.com
dist: trusty
cache: packages
warnings_are_errors: false

r:
  - release
  - devel
  - oldrel

notifications:
  email:
    on_success: change
    on_failure: change
